### PR TITLE
fix for Could not receive media list

### PR DESCRIPTION
**Pull request by daniel3xxx**
Fix outdated urls (thanks to @kriswo)

### CODE REVIEW

**Comment by markop159** [comment]
For me old link still works, do not know why. :)

This is only for movies, can you please add changes for tv shows as well? As I can see you only need to change /tv/shows/ to /shows/.

I cannot test this right now. Will merge this as soon as I can find some time to test this changes.

**Comment by daniel3xxx** [comment]
Try cleaning cache or uninstall and install again the add-on. After that the add-on do not work. I tried the changes for tv shows but still not working (unknown error in kodi)

**Comment by S0und** [comment]
```
2020-03-28 19:46:22.514 T:4153 ERROR: [plugin.video.kodipopcorntime] (Thread-1) (URL) HTTPError: Received wrong status code (404 Not Found) from https://api-fetch.website/tv/movies/1?genre=all&sort=trending&order=-1 - https://api-fetch.website/tv/movies/1?genre=all&sort=trending&order=-1 2020-03-28 19:46:22.514 T:4153 NOTICE: [plugin.video.kodipopcorntime] (Thread-1) (URL) Proxy domain 'https://api-fetch.website' is not working and will therefore have low priority in the future
```

This API is not working for me either. Even after I cleared everything. Honestly if there is a newer version which probably indicate that the older one will be phased out after a while, switching to the newer would be appropriate.

**Comment by markop159** [comment]
Thank you for your work, will test it and try to fix tv shows as well. Will try to upload new version to repository soon.

**Pull request merged**
